apiVersion: v1
kind: Secret
metadata:
  name: explorer-server-secrets
data:
  DATABASE_PASSWORD: KytrTFJHPS5NbS1HbS5NbS1H5NbS1HbQ==
  SOLANA_API_KEY: KytrTFJHPS5NbS1HbS5NbS1H5NbS1HbQ==
  SOLANA_WALLET_PRIVATE_KEY: KytrTFJHPS5NbS1HbS5NbS1H5NbS1HbQ==
---   