
name: Deploy Web explorer to AKS

on:
  push:
    branches: [ main, develop ]

env:
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Set environment variables
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "RESOURCE_GROUP=wayru-prod" >> $GITHUB_ENV
          echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          echo "AKS_CLUSTER_NAME=backends-cluster-prod-2" >> $GITHUB_ENV
          
        else
          echo "RESOURCE_GROUP=wayru-dev" >> $GITHUB_ENV
          echo "DEPLOY_ENV=develop" >> $GITHUB_ENV
          echo "AKS_CLUSTER_NAME=backends-cluster-dev-1" >> $GITHUB_ENV
          
        fi
    
    - name: Build and push image with secrets
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        no-cache: true
        tags: ${{ env.CONTAINER_REGISTRY }}/explorer-server:${{ env.DEPLOY_ENV }}-${{ env.IMAGE_TAG }}
    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}

    - name: Deploy to AKS
      env:
        CONTAINER_IMAGE: ${{ env.CONTAINER_REGISTRY }}/web-explorer:${{ env.DEPLOY_ENV }}-${{ env.IMAGE_TAG }}
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          # Replace placeholders in deployment files
          sed -i "s|\${CONTAINER_REGISTRY}/web-explorer:\${IMAGE_TAG}|$CONTAINER_IMAGE|g" kubernetes/prod/deployment.yaml
          # sed -i "s|\${DOMAIN_NAME}|$DOMAIN_NAME|g" kubernetes/prod/ingress.yaml
        
          # Apply Kubernetes configurations
          kubectl apply -f kubernetes/prod/deployment.yaml
          kubectl apply -f kubernetes/prod/service.yaml
          # kubectl apply -f kubernetes/prod/ingress.yaml  
        else
          # Replace placeholders in deployment files
          sed -i "s|\${CONTAINER_REGISTRY}/web-explorer:\${IMAGE_TAG}|$CONTAINER_IMAGE|g" kubernetes/develop/deployment.yaml
          # sed -i "s|\${DOMAIN_NAME}|$DOMAIN_NAME|g" kubernetes/develop/ingress.yaml
        
          # Apply Kubernetes configurations
          kubectl apply -f kubernetes/develop/deployment.yaml
          kubectl apply -f kubernetes/develop/service.yaml
          # kubectl apply -f kubernetes/develop/ingress.yaml
        fi
